import React from 'react';
import Head from 'next/head';
import Sidebar from './Sidebar';

const Layout = ({children}) => {
  return (
    <>
      <Head>
        <title>CRM - Backoffice</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />
        <meta name="description" content="Generated by create next app for CRM administration" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen">
        <Sidebar className="bg-gray-800 min-h-screen"/>
        {children}
      </main>
    </>
  )
}

export default Layout;
